(() => {
 'use strict';
 const PROFILE=window.GameProfile, DATA=window.GAME_DATA, ALL=DATA.flatMap(s=>s.items), KEY=PROFILE?.storageKey||'mtt-tu-luyen-1-v1', app=document.getElementById('app');
 let save={done:[],review:[],first:[]}, storageOK=true;
 try { const raw=JSON.parse(localStorage.getItem(KEY)||'null'); if(raw) for(const k of ['done','review','first']) save[k]=[...new Set((Array.isArray(raw[k])?raw[k]:[]).filter(id=>ALL.some(q=>q.id===id)))]; } catch {storageOK=false;}
 let station=null, queue=[], position=0, reviewing=false, state={}, lastFocus=null;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shuffle=a=>a.map(x=>({x,n:Math.random()})).sort((a,b)=>a.n-b.n).map(o=>o.x);
 // Keep answers away from their matching row; generate once per puzzle.
 function matchOrder(length){
  const ids=Array.from({length},(_,i)=>i);
  if(length<2)return ids;
  for(let attempt=0;attempt<24;attempt++){
   const order=shuffle(ids);
   if(order.every((id,row)=>id!==row))return order;
  }
  const offset=1+Math.floor(Math.random()*(length-1));
  return ids.map((_,i)=>ids[(i+offset)%length]);
 }
 const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(save));}catch{storageOK=false;}};
 const icon=(type)=>({bag:'<rect x="25" y="34" width="70" height="68" rx="17"/><path d="M44 34v-9a16 16 0 0 1 32 0v9M38 57h44M38 72h44v20H38z"/><path d="M94 51h10v40H94M25 51H15v40h10"/>',tools:'<path d="m29 94 51-64 15 12-51 64-20 7zM75 36l15 12M29 94l15 12"/><path d="m22 31 14-14 65 64-14 15zM41 25l-6 6M55 39l-6 6M69 53l-6 6"/>',flag:'<path d="M31 107V20M32 22c23-18 39 19 65 0v51c-26 19-43-18-65 0M17 108h29"/><path d="m57 42 6 11 12 2-9 8 2 12-11-6-11 6 2-12-9-8 12-2z"/>'}[type]||'');
 const drawing=type=>`<svg viewBox="0 0 120 120" aria-hidden="true">${icon(type)}</svg>`;
 const robot=(mood='welcome')=>`<button type="button" class="mascot" data-mood="${mood}" data-say="Hello! I'm Titi. Let's learn together!" aria-label="Nghe Titi, cáo khám phá, chào con" title="Bấm để nghe Titi chào con"></button>`;
 const objectIcon=word=>({ruler:'📏',pencil:'✏️',book:'📖',notebook:'📓'}[word]||'✦');
 function world(s,small=false){const n=s.items.filter(q=>save.done.includes(q.id)).length;return `<div class="world-object ${s.id} ${small?'small':''}" aria-hidden="true">${s.id==='words'?drawing('bag'):s.id==='sentences'?'<div class="train-engine"><i></i><b>ABC</b></div><div class="train-car">?</div>':'<div class="club-house"><span>WELCOME</span><i></i><i></i><b>★</b></div>'}<span class="world-shadow"></span></div>`;}
 function hud(){return `<div class="game-hud">${PROFILE?`<span class="player-name">Đang chơi: <b>${esc(PROFILE.displayName)}</b></span>`:""}<span class="star-wallet">★ <b>${save.done.length}</b><small>/ ${ALL.length} sao</small></span><span class="game-badges">${DATA.map(s=>`<span class="${s.items.every(q=>save.done.includes(q.id))?'collected':''}" title="${esc(s.name)}">${s.id==='words'?'🎒':s.id==='sentences'?'🚂':'🏰'}</span>`).join('')}</span></div>`;}
 function focusTitle(){const h=app.querySelector('h1')||app.querySelector('h2');if(h){h.tabIndex=-1;h.focus({preventScroll:true});}window.scrollTo({top:0,behavior:'instant'});}
 function home(focus=false){window.GameAudio.stop();station=null;reviewing=false;const stamps=DATA.filter(s=>s.items.every(q=>save.done.includes(q.id))).length;
 app.innerHTML=`<div class="game-titlebar"><div><div class="eyebrow">TỰ LUYỆN 1 · TỪ VỰNG & NGỮ PHÁP</div><h1>Biệt đội đón bạn mới</h1></div>${hud()}</div><section class="adventure-map" aria-label="Bản đồ ba địa điểm chơi"><div class="sky-cloud cloud-one"></div><div class="sky-cloud cloud-two"></div><div class="map-sun">✦</div><div class="map-label">THE WELCOME CLUB</div><div class="hill hill-back"></div><div class="hill hill-front"></div><svg class="map-trail" viewBox="0 0 1100 400" preserveAspectRatio="none" aria-hidden="true"><path d="M130 335 C200 90 440 400 535 210 S850 100 950 255"/></svg><div class="map-locations">${DATA.map(s=>{const n=s.items.filter(q=>save.done.includes(q.id)).length;return `<button class="map-location ${s.id}" data-station="${s.id}" aria-label="Chơi ${s.name}"><span class="location-number">${n===s.items.length?'✓':s.number}</span>${world(s)}<span class="location-sign"><b>${s.name}</b><small>${n}/${s.items.length} ★ · ${s.id==='words'?'Tìm đồ & ghép thẻ':s.id==='sentences'?'Lắp tàu & xếp toa':'Mở cửa bằng manh mối'}</small></span></button>`;}).join('')}</div><div class="map-pip">${robot()}<div class="speech-bubble"><b>Titi · Cáo khám phá của Ms Trang Trieu</b><span>${PROFILE?`Chào ${esc(PROFILE.displayName)}!<br>`:""}Cùng Titi khám phá và thu thập ngôi sao nhé!<br>Bấm một địa điểm để vào chơi!</span></div></div><span class="map-flower f1">✿</span><span class="map-flower f2">✿</span><span class="map-flower f3">✿</span></section><section class="game-start"><p><span>★ ${stamps}/3 huy hiệu</span> Chơi khoảng 10–15 phút · Thử lại thoải mái</p><button class="primary" id="start">${save.done.length?'Chơi tiếp':'Lên đường!'} <span>→</span></button></section>
 <section class="review-strip"><span class="review-icon">↺</span><div><h3>Luyện lại cùng Titi</h3><p>${save.review.length?`${save.review.length} nhiệm vụ cần nhớ. Tự vượt qua để Titi cất vào sổ đã nhớ!`:'Titi sẽ giữ lại những nhiệm vụ con cần trợ giúp để cùng luyện thêm.'}</p></div><button class="secondary" id="review" ${save.review.length?'':'disabled'}>Ôn lại${save.review.length?' · '+save.review.length:''} →</button></section><div class="save-note"><span>${storageOK?(PROFILE?'Tiến độ của hồ sơ này lưu riêng trên trình duyệt · Chưa gửi điểm cho giáo viên.':'Tiến độ lưu trên trình duyệt này · Chưa gửi điểm cho giáo viên.'):'Trình duyệt chưa cho phép lưu. Tiến độ chỉ giữ trong lần mở này.'}</span><button class="text-button" id="reset">Bắt đầu lượt mới</button></div>`;
 document.getElementById('start').onclick=()=>start(DATA.find(s=>s.items.some(q=>!save.done.includes(q.id)))||DATA[0]);
 app.querySelectorAll('[data-station]').forEach(b=>b.onclick=()=>start(DATA.find(s=>s.id===b.dataset.station)));
 document.getElementById('review').onclick=()=>{reviewing=true;station=null;queue=ALL.filter(q=>save.review.includes(q.id));position=0;init();};
 document.getElementById('reset').onclick=resetDialog;if(focus)focusTitle();
 }
 function resetDialog(){const d=document.createElement('dialog');d.innerHTML='<h2>Bắt đầu lượt mới?</h2><p>Thao tác này xóa huy hiệu và tiến độ Tự luyện 1 của lượt chơi hiện tại trên trình duyệt này.</p><div class="dialog-actions"><button class="secondary" id="cancel-reset">Giữ tiến độ</button><button class="primary" id="confirm-reset">Bắt đầu lượt mới</button></div>';document.body.append(d);d.querySelector('#cancel-reset').onclick=()=>d.close();d.querySelector('#confirm-reset').onclick=()=>{save={done:[],review:[],first:[]};persist();d.close();home(true);};d.onclose=()=>d.remove();d.showModal();}
 function start(s){station=s;reviewing=false;queue=s.items;position=Math.max(0,queue.findIndex(q=>!save.done.includes(q.id)));init();}
 function current(){return queue[position];}
 function init(){window.GameAudio.stop();state={wrong:false,hint:false,solved:false,selected:null,pairs:[],placed:[],order:[],rejected:[],packIndex:0,packed:[],rightOrder:current().type==='match'?matchOrder(current().pairs.length):shuffle((current().pairs||[]).map((_,i)=>i)),cardOrder:shuffle((current().cards||[]).map((_,i)=>i))};render();focusTitle();}
 function flag(){const id=current().id;if(!save.review.includes(id))save.review.push(id);persist();}
 function feedback(text,kind='wrong'){const e=document.getElementById('feedback');e.className='feedback '+kind;e.innerHTML=text;e.hidden=false;const mascot=app.querySelector('.mascot');if(mascot)mascot.dataset.mood=kind==='wrong'?'encourage':kind==='correct'?'cheer':'welcome';if(kind==='neutral'&&/✓|🎒/.test(text))window.GameAudio.sound('pair');}
 function mistake(message){state.wrong=true;flag();window.GameAudio.sound('retry');feedback(`<strong>Úi, thử lại cùng Titi nhé!</strong> ${message}`);}
 function success(){if(state.solved)return;state.solved=true;const q=current();state.newStar=!save.done.includes(q.id);if(state.newStar){save.done.push(q.id);if(!state.wrong&&!state.hint)save.first.push(q.id);}if(reviewing&&!state.wrong&&!state.hint)save.review=save.review.filter(id=>id!==q.id);persist();render();window.GameAudio.sound('correct');if(q.type==='order')window.GameAudio.say(q.answer.join(' ')+q.punct);feedback(`<strong>★ ${state.newStar?'Ting ting! Một ngôi sao cho con!':'Titi đập tay nào! Vượt qua rồi!'}</strong> ${esc(q.why)}`,'correct');document.getElementById('next').focus({preventScroll:true});}
 function render(){const q=current(),s=station||DATA.find(s=>s.items.includes(q));const active=document.activeElement;const keepFocus=active?.dataset?Object.entries(active.dataset).find(([k])=>['left','right','card','group','token','remove','object'].includes(k)):null;
 app.innerHTML=`<div class="play-nav"><button class="secondary" id="home">← Bản đồ</button><span>${reviewing?'LUYỆN LẠI CÙNG TITI':esc(s.name)} · ${position+1}/${queue.length}</span>${hud()}</div><section class="game-arena arena-${s.id} ${state.solved?'celebrating':''}"><div class="arena-top"><span class="level-tag">MÀN ${String(position+1).padStart(2,'0')} / ${queue.length}</span><div class="level-stars">${queue.map((a,i)=>`<span class="${i===position?'active':save.done.includes(a.id)?'done':''}" title="Nhiệm vụ ${i+1}">${save.done.includes(a.id)?'★':i+1}</span>`).join('')}</div></div><div class="game-scene"><div class="scene-guide">${robot(state.solved?'cheer':'welcome')}<div class="speech-bubble"><b>${state.solved?'Tuyệt! Mình đi tiếp nào!':q.title}</b><span>${esc(q.prompt)}</span></div></div>${world(s,true)}${state.solved?'<div class="star-burst" aria-hidden="true"><span>★</span><i>✦</i><i>✦</i><i>✦</i></div>':''}</div><div class="game-workbench"><h1 class="sr-only">${esc(q.title)}</h1>${q.scene?`<div class="scene" lang="en"><span class="scene-pin">✉</span>${q.scene}</div>`:''}<div id="interaction">${interaction(q)}</div><aside id="pronunciation-panel" class="pronunciation-panel" aria-label="Nghe và nghĩa của từ"></aside><div id="feedback" role="status" aria-live="polite" class="feedback" hidden></div><div class="hint-box" ${state.hint?'':'hidden'}><b>Titi mách nhỏ</b><p>${esc(q.hint)}</p></div><div class="puzzle-bottom"><button class="text-button" id="hint" ${state.solved?'disabled':''}>${state.hint?'✓ Đã nhờ Titi':'☀ Nhờ Titi giúp'}</button><button class="primary" id="next" ${state.solved?'':'disabled'}>${position===queue.length-1?'Nhận huy hiệu':'Đi tiếp'} →</button></div></div></section>`;
 document.getElementById('home').onclick=()=>home(true);
 document.getElementById('hint').onclick=()=>{state.hint=true;flag();app.querySelector('.hint-box').hidden=false;document.getElementById('hint').textContent='✓ Đã mở gợi ý';};
 document.getElementById('next').onclick=()=>{if(!state.solved)return;if(position+1<queue.length){position++;init();}else finish();};bind(q);if(keepFocus&&!state.solved){const [k,v]=keepFocus;const e=app.querySelector(`[data-${k}="${v}"]`);if(e&&!e.disabled)e.focus({preventScroll:true});else app.querySelector('[data-token]:not(:disabled),[data-left]:not(:disabled),[data-card]:not(:disabled),#check:not(:disabled)')?.focus({preventScroll:true});}
 }
 function interaction(q){const disabled=state.solved?'disabled':'';
 if(q.type==='pack')return `<div class="pack-board"><div class="clue-tag"><span>MANH MỐI ${Math.min(state.packIndex+1,q.pairs.length)}/${q.pairs.length}</span><b lang="en">${state.solved?'Ready for school!':esc(q.pairs[state.packIndex][0])}</b></div><div class="pack-play"><div class="object-shelf">${state.rightOrder.map(i=>`<button class="school-object ${state.selected===i?'selected':''} ${state.packed.includes(i)?'packed':''}" data-object="${i}" aria-label="Chọn ${esc(q.pairs[i][1])}" ${state.packed.includes(i)?'disabled':''}><span aria-hidden="true">${objectIcon(q.pairs[i][1])}</span><b lang="en">${esc(q.pairs[i][1])}</b></button>`).join('')}</div><button class="bag-target ${state.solved?'full':''}" id="pack-bag" aria-label="Cất đồ đã chọn vào cặp" ${disabled}>${drawing('bag')}<span>${state.solved?'Đã đủ đồ!':state.selected!==null?'↓ Cất vào cặp':'Chọn đồ trước nhé'}</span><small>${state.packed.length}/${q.pairs.length} món</small></button></div><div class="inventory" aria-label="Đồ đã cất">${q.pairs.map((p,i)=>`<span class="${state.packed.includes(i)?'filled':''}">${state.packed.includes(i)?objectIcon(p[1]):'?'}</span>`).join('')}</div></div>`;
 if(q.type==='choice'||q.type==='repair')return `<p class="micro">${q.type==='repair'?'Chọn mảnh ghép thay cho từ in đậm để sửa lời nhắn.':'Chọn cánh cửa có lời giải đúng để đi tiếp.'}</p><div class="answer-doors ${q.type==='repair'?'repair-doors':''}">${q.options.map((o,i)=>`<button class="answer-door ${state.solved&&o===q.answer?'opened':''} ${state.rejected.includes(i)?'rejected':''}" data-choice="${i}" ${disabled||state.rejected.includes(i)?'disabled':''}><span class="door-symbol" aria-hidden="true">${q.type==='repair'?'⚙':state.solved&&o===q.answer?'★':['☀','☾','✦'][i]}</span><span class="door-label" lang="en">${esc(o)}</span><i class="door-knob" aria-hidden="true"></i>${state.solved&&o===q.answer?'<b class="door-result">ĐÃ MỞ ✓</b>':''}</button>`).join('')}</div>`;
 if(q.type==='match')return `<p class="micro">Bấm một thẻ bên trái, rồi bấm thẻ ghép đôi bên phải.</p><div class="match-grid"><div>${q.pairs.map((p,i)=>`<button class="match-card ${state.selected===i?'selected':''} ${state.pairs.includes(i)?'matched':''}" data-left="${i}" ${state.pairs.includes(i)?'disabled':''} aria-pressed="${state.selected===i}" lang="en">${esc(p[0])}${state.pairs.includes(i)?' ✓':''}</button>`).join('')}</div><div>${state.rightOrder.map(i=>`<button class="match-card ${state.pairs.includes(i)?'matched':''}" data-right="${i}" ${state.pairs.includes(i)?'disabled':''} lang="en">${esc(q.pairs[i][1])}${state.pairs.includes(i)?' ✓':''}</button>`).join('')}</div></div>`;
 if(q.type==='sort')return `<p class="micro">Mỗi thẻ là một hành khách. Bấm thẻ, rồi bấm đúng toa tàu.</p><div class="word-bank ticket-bank">${state.cardOrder.map(i=>`<button class="chip ${state.selected===i?'selected':''}" data-card="${i}" ${state.placed.includes(i)?'disabled':''} aria-pressed="${state.selected===i}" lang="en">${esc(q.cards[i][0])}${state.placed.includes(i)?' ✓':''}</button>`).join('')}</div><div class="bins train-bins ${state.solved?'departing':''}">${q.groups.map(g=>`<button class="bin train-bin" data-group="${g}" ${disabled} aria-label="Ngăn ${g}"><b>${g.toUpperCase()}</b><span>${state.placed.filter(i=>q.cards[i][1]===g).map(i=>`<i>${esc(q.cards[i][0])}</i>`).join('')||'Bấm để lên tàu'}</span><em class="wheels" aria-hidden="true"></em></button>`).join('')}</div><div class="train-track" aria-hidden="true"></div>`;
 return `<p class="micro">Bấm các toa theo thứ tự để lắp câu. Bấm toa đã lắp để tháo ra.</p><div class="sentence-train ${state.solved?'departing':''}"><span class="little-engine" aria-hidden="true">🚂</span><div class="sentence-slot" aria-label="Câu con đang xếp">${state.order.map((i,n)=>`<button class="chip placed" data-remove="${n}" ${disabled} lang="en" aria-label="Bỏ ${esc(q.tokens[i])}">${esc(q.tokens[i])}</button>`).join('')||'<span>Lắp các toa vào đây…</span>'}<b>${q.punct}</b></div></div><div class="word-bank carriage-bank">${q.tokens.map((t,i)=>`<button class="chip" data-token="${i}" ${disabled||state.order.includes(i)?'disabled':''} lang="en">${esc(t)}</button>`).join('')}</div><button class="primary check" id="check" ${state.solved||state.order.length!==q.tokens.length?'disabled':''}>🚦 Cho tàu chạy</button>`;
 }
 function bind(q){app.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.choice);if(q.options[n]===q.answer)success();else{state.rejected.push(n);render();mistake('Đáp án này chưa khớp. Đọc lại tình huống hoặc mở gợi ý.');}});
 app.querySelectorAll('[data-object]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.object);render();});const pack=document.getElementById('pack-bag');if(pack)pack.onclick=()=>{if(state.selected===null){feedback('Chọn một món đồ trên kệ rồi bấm chiếc cặp nhé.','neutral');return;}if(state.selected===state.packIndex){state.packed.push(state.selected);state.packIndex++;state.selected=null;if(state.packIndex===q.pairs.length)success();else{render();feedback('🎒 Đã cất một món! Đọc manh mối tiếp theo nhé.','neutral');}}else{state.selected=null;render();mistake('Món này chưa hợp với manh mối. Tìm đồ đúng công dụng nhé.');}};
 app.querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.left);render();});
 app.querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>{if(state.selected===null){feedback('Chọn một thẻ bên trái trước nhé.','neutral');return;}if(state.selected===Number(b.dataset.right)){state.pairs.push(state.selected);state.selected=null;if(state.pairs.length===q.pairs.length)success();else{render();feedback('✓ Một cặp đúng! Ghép tiếp các thẻ còn lại.','neutral');}}else{state.selected=null;render();mistake('Hai thẻ này chưa thành một cặp. Con thử ghép lại nhé.');}});
 app.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{state.selected=Number(b.dataset.card);render();});
 app.querySelectorAll('[data-group]').forEach(b=>b.onclick=()=>{if(state.selected===null){feedback('Chọn một thẻ thời gian trước nhé.','neutral');return;}if(q.cards[state.selected][1]===b.dataset.group){state.placed.push(state.selected);state.selected=null;if(state.placed.length===q.cards.length)success();else{render();feedback('✓ Đúng ngăn rồi! Tiếp tục với thẻ khác.','neutral');}}else{render();mistake('Ngăn này chưa phù hợp. Xác định xem đây là thứ, tháng, năm, giờ hay buổi.');}});
 app.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{state.order.push(Number(b.dataset.token));render();});
 app.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.order.splice(Number(b.dataset.remove),1);render();});
 const check=document.getElementById('check');if(check)check.onclick=()=>{if(state.order.map(i=>q.tokens[i]).join(' ')===q.answer.join(' '))success();else mistake('Thứ tự chưa đúng. Bấm vào thẻ trong câu để lấy ra rồi xếp lại.');};
 const reads={choice:i=>q.options[i],object:i=>q.pairs[i][1],left:i=>q.pairs[i][0],right:i=>q.pairs[i][1],card:i=>q.cards[i][0],group:g=>g,token:i=>q.tokens[i],remove:i=>q.tokens[state.order[i]]};
 for(const [key,getText] of Object.entries(reads))app.querySelectorAll(`[data-${key}]`).forEach(b=>{b.dataset.say=getText(b.dataset[key]);});
 window.GameAudio.mount();
 }
 function finish(){const isReview=reviewing;const pending=queue.filter(q=>save.review.includes(q.id));app.innerHTML=`<section class="finish"><div class="completion-mascot">${robot('cheer')}</div><div class="eyebrow">${isReview?'ĐÃ HOÀN THÀNH LƯỢT ÔN':'HUY HIỆU MỚI CỦA CON'}</div><h1>${isReview?'Mỗi lần thử, hiểu thêm.':esc(station.reward)}</h1><p>${isReview?'Con đã đi hết các câu trong lượt ôn này.':`Con đã hoàn thành chặng “${esc(station.name)}”. Đọc lại điều cần nhớ trước khi khám phá chặng tiếp theo nhé.`}</p><div class="takeaway"><b>Mang theo điều này</b><p>${isReview?'Tìm manh mối trong tình huống trước khi chọn đáp án.':station.id==='words'?'Địa chỉ, quê hương và quốc tịch là những thông tin khác nhau. Chọn từ đúng với ý con muốn nói.':station.id==='sentences'?'Where hỏi nơi chốn; Whose hỏi của ai. Dùng on + thứ, in + tháng/năm và at + giờ.':'Đọc câu hỏi trước. Chọn thông tin trả lời đúng điều người hỏi cần biết.'}</p></div><p class="result-note">${pending.length?`${pending.length} thử thách trong lượt này còn ở mục Luyện lại cùng Titi. Con có thể luyện thêm khi sẵn sàng.`:'Con đã tự tìm đúng các đáp án mà không cần gợi ý trong lượt đầu hoặc lượt ôn.'}</p><div class="finish-actions"><button class="primary" id="finish-home">Về bản đồ hành trình →</button>${!isReview&&DATA.indexOf(station)<2?'<button class="secondary" id="next-station">Khám phá chặng tiếp</button>':''}</div></section>`;
 window.GameAudio.stop();window.GameAudio.sound('finish');document.getElementById('finish-home').onclick=()=>home(true);const b=document.getElementById('next-station');if(b)b.onclick=()=>start(DATA[DATA.indexOf(station)+1]);focusTitle();}
 document.getElementById('help').onclick=()=>{lastFocus=document.activeElement;document.getElementById('help-dialog').showModal();};document.getElementById('close-help').onclick=()=>document.getElementById('help-dialog').close();document.getElementById('help-dialog').onclose=()=>lastFocus?.focus();document.querySelector('.brand').onclick=e=>{e.preventDefault();home(true);};home();
})();
