window.GAME_DATA = [
 {id:'words',number:'01',name:'Xưởng cặp sách',english:'PACK YOUR BAG',icon:'bag',color:'coral',subtitle:'Ghép manh mối. Chọn đúng đồ. Sẵn sàng đến lớp!',reward:'Word Detective',items:[
  {id:'w1',type:'match',title:'Bốn dòng trên thẻ bạn mới',prompt:'Ghép thông tin với đúng tên gọi.',pairs:[['Mia','name'],['18 Green Street','address'],['My home town is Hue.','hometown'],['I am Vietnamese.','nationality']],hint:'Tên, địa chỉ, quê hương và quốc tịch là bốn loại thông tin khác nhau.',why:'name = tên; address = địa chỉ cụ thể; hometown = quê hương; nationality = quốc tịch. “Vietnamese” là quốc tịch; “Viet Nam” là tên nước.'},
  {id:'w2',type:'pack',title:'Chiếc cặp còn thiếu gì?',prompt:'Đọc manh mối, chọn đồ phù hợp rồi bấm chiếc cặp để cất vào.',pairs:[['Draw a straight line.','ruler'],['Write, then erase a mistake.','pencil'],['Read a story.','book'],['Write notes on blank pages.','notebook']],hint:'straight line = đường thẳng; erase = tẩy; blank pages = những trang chưa viết.',why:'ruler = thước; pencil = bút chì; book = sách để đọc; notebook = vở để ghi chép. Cùng là đồ dùng học tập nhưng mỗi món có công dụng khác nhau.'},
  {id:'w3',type:'choice',title:'Đọc đúng dòng trên thẻ',scene:'Hometown: Da Nang<br>Address now: 26 Lake Street, Ha Noi',prompt:'Which city is this child’s hometown?',options:['Ha Noi','Da Nang','Lake Street'],answer:'Da Nang',hint:'Tìm quê hương, không phải nơi ở hiện tại.',why:'Đáp án là Da Nang. “Hometown” chỉ quê hương. Dòng “Address now” cho biết địa chỉ hiện tại; hai thông tin này không nhất thiết giống nhau.'},
  {id:'w4',type:'choice',title:'Cửa lớp đang mở',scene:'Ben is at the door. The teacher wants him to enter the classroom.',prompt:'What does the teacher say?',options:['Go out, please.','Sit down, please.','Come in, please.'],answer:'Come in, please.',hint:'enter = đi vào. Ben vẫn đang ở cửa.',why:'“Come in, please.” = Mời em vào. “Go out” là đi ra; “sit down” là ngồi xuống. Cần chọn hành động phù hợp với tình huống.'},
  {id:'w5',type:'match',title:'Đổi chiều hành động',prompt:'Ghép mỗi khẩu lệnh với hành động ngược lại.',pairs:[['stand up','sit down'],['open your book','close your book'],['come in','go out']],hint:'Tìm từng cặp: đứng–ngồi, mở–đóng, vào–ra.',why:'stand up / sit down = đứng lên / ngồi xuống; open / close your book = mở / đóng sách; come in / go out = đi vào / đi ra.'},
  {id:'w6',type:'choice',title:'Mang mọi thứ đến lớp',scene:'Mia has a book, a notebook and three pencils. She wants to carry them together.',prompt:'What does she need?',options:['A ruler.','A school bag.','A pen.'],answer:'A school bag.',hint:'carry them together = mang tất cả những món đó cùng nhau.',why:'A school bag = một chiếc cặp sách, dùng để mang đồ dùng. Ruler (thước) và pen (bút) cũng là đồ dùng học tập nhưng không giúp đựng những món này.'}
 ]},
 {id:'sentences',number:'02',name:'Ga câu chữ',english:'BUILD IT RIGHT',icon:'tools',color:'gold',subtitle:'Xếp câu hỏi. Sửa lời nhắn. Sắp lịch thật chuẩn.',reward:'Sentence Builder',items:[
  {id:'g1',type:'sort',title:'Ba ngăn thời gian',prompt:'Chọn một thẻ, rồi chọn ngăn IN, ON hoặc AT.',groups:['in','on','at'],cards:[['Monday','on'],['May','in'],['7:30','at'],['2027','in'],['the morning','in'],['night','at']],hint:'Thứ → on; tháng/năm/buổi sáng → in; giờ và night → at.',why:'on Monday; in May; at 7:30; in 2027; in the morning; at night. Chú ý cặp dễ nhầm: in the morning nhưng at night.'},
  {id:'g2',type:'order',title:'Hỏi chỗ ở',scene:'Mia: “I live in Hue.”',prompt:'Xếp các thẻ thành câu hỏi phù hợp.',tokens:['you','Where','live','do'],answer:['Where','do','you','live'],punct:'?',hint:'Bắt đầu bằng Where. Sau từ để hỏi là do + you + động từ.',why:'Where do you live? = Bạn sống ở đâu? Dùng Where để hỏi nơi chốn. Động từ live đi sau “do you” và giữ nguyên dạng.'},
  {id:'g3',type:'match',title:'Mỗi câu trả lời, một từ để hỏi',prompt:'Ghép câu hỏi còn trống với từ phù hợp.',pairs:[['___ is your teacher? — Ms Lan.','Who'],['___ pencil is this? — It’s Ben’s.','Whose'],['___ are you late? — Because I missed the bus.','Why'],['___ is your house? — Near the park.','Where']],hint:'Ai? Của ai? Tại sao? Ở đâu?',why:'Who hỏi người; Whose hỏi chủ sở hữu; Why hỏi lý do (thường trả lời bằng Because); Where hỏi địa điểm. “Ben’s” nghĩa là của Ben.'},
  {id:'g4',type:'repair',title:'Sửa lịch câu lạc bộ',scene:'The club meets <strong>in</strong> Friday.',prompt:'Thay từ in bằng từ đúng.',options:['on','at','of'],answer:'on',hint:'Friday là một thứ trong tuần.',why:'Câu đúng: The club meets on Friday. Dùng on trước thứ/ngày cụ thể; in thường đi với tháng/năm; at đi với giờ.'},
  {id:'g5',type:'order',title:'Hỏi quốc tịch',scene:'Ben: “I am British.”',prompt:'Xếp câu hỏi về quốc tịch của Ben.',tokens:['you','nationality','are','What'],answer:['What','nationality','are','you'],punct:'?',hint:'What nationality + are + you?',why:'What nationality are you? = Bạn mang quốc tịch gì? “British” là quốc tịch. Câu hỏi này dùng are, không thêm do.'},
  {id:'g6',type:'match',title:'Cùng là “bao nhiêu”, nhưng khác nhau',prompt:'Đọc câu trả lời rồi chọn cách hỏi.',pairs:[['___ pencils are in the bag? — Three.','How many'],['___ is this notebook? — 20,000 dong.','How much'],['___ is the lesson? — Forty minutes.','How long'],['___ do you read? — Every evening.','How often']],hint:'Đếm số lượng, hỏi giá, hỏi thời lượng hay hỏi tần suất?',why:'How many + danh từ đếm được số nhiều; How much hỏi giá (ở câu này); How long hỏi thời lượng; How often hỏi tần suất. “Every evening” = mỗi tối, không phải thời lượng.'},
  {id:'g7',type:'repair',title:'Lời nhắn buổi tối',scene:'Please call me <strong>in</strong> night.',prompt:'Thay từ in bằng từ đúng.',options:['on','at','to'],answer:'at',hint:'Cụm từ cố định để nói “vào ban đêm” là gì?',why:'Câu đúng: Please call me at night. Ta dùng at night nhưng in the morning / afternoon / evening. Không suy ra rằng mọi buổi trong ngày đều dùng in.'},
  {id:'g8',type:'choice',title:'Thứ hay ngày tháng?',scene:'Ben: “It’s Tuesday.”',prompt:'Which question does Ben answer?',options:['What is the date today?','What day is it today?','What time is it?'],answer:'What day is it today?',hint:'Tuesday là thứ Ba, không phải ngày tháng hay giờ.',why:'What day is it today? hỏi thứ. What is the date today? hỏi ngày tháng. What time is it? hỏi giờ. Hãy phân biệt day, date và time.'}
 ]},
 {id:'mission',number:'03',name:'Cổng câu lạc bộ',english:'THE WELCOME CLUB',icon:'flag',color:'mint',subtitle:'Gặp Leo, nhân vật trong câu chuyện, và giúp bạn tìm đúng lớp.',reward:'Welcome Hero',items:[
  {id:'m1',type:'choice',title:'01 · Đúng bạn, đúng thông tin',scene:'Leo’s card<br><strong>From:</strong> Australia<br><strong>Lives in:</strong> Ha Noi<br><strong>Club:</strong> Welcome Club',prompt:'Leo là bạn nhỏ trong câu chuyện. “Where are you from?” — Leo says:',options:['I live in Ha Noi.','I’m from Australia.','I’m in the Welcome Club.'],answer:'I’m from Australia.',hint:'from hỏi nơi xuất thân; live in hỏi nơi đang sống.',why:'“I’m from Australia.” trả lời đúng câu hỏi. Ha Noi là nơi Leo đang sống; Welcome Club là tên câu lạc bộ. Australia = nước Úc.'},
  {id:'m2',type:'sort',title:'02 · Hoàn thiện vé hẹn',scene:'WELCOME CLUB · Friday · 8:00 · October',prompt:'Đặt từng thông tin vào đúng giới từ để Leo đọc lời hẹn.',groups:['in','on','at'],cards:[['Friday','on'],['8:00','at'],['October','in']],hint:'Tìm thứ, giờ và tháng.',why:'See you on Friday, at 8:00, in October. Dùng on + thứ, at + giờ, in + tháng. October = tháng Mười.'},
  {id:'m3',type:'choice',title:'03 · Chọn đúng câu hỏi',scene:'There are two bags, a red one and a blue one. Leo says, “The blue one is mine.”',prompt:'What do you ask Leo?',options:['Whose bag is this?','Which bag is yours?','How many bags are there?'],answer:'Which bag is yours?',hint:'Con muốn Leo chọn một trong hai chiếc cặp.',why:'Which bag is yours? = Chiếc cặp nào là của bạn? Which giúp chọn trong các lựa chọn đã có. Whose hỏi chủ sở hữu của một chiếc cặp; How many hỏi số lượng.'},
  {id:'m4',type:'order',title:'04 · Hỏi giờ bắt đầu',scene:'Leo needs to know the time. “The club starts at eight.”',prompt:'Ghép câu hỏi Leo cần dùng.',tokens:['start','the club','does','What time'],answer:['What time','does','the club','start'],punct:'?',hint:'What time + does + the club + start?',why:'What time does the club start? = Câu lạc bộ bắt đầu lúc mấy giờ? Sau does, động từ start giữ nguyên dạng. “At eight” cho biết giờ cụ thể.'},
  {id:'m5',type:'choice',title:'05 · Cả lớp đã sẵn sàng',scene:'Leo is in the classroom. His book is open. The teacher says, “Close your book, please.”',prompt:'What should Leo do?',options:['Shut his book.','Open his notebook.','Leave the classroom.'],answer:'Shut his book.',hint:'shut và close cùng mang nghĩa “đóng”.',why:'Leo cần đóng sách: Shut his book. Câu lệnh không yêu cầu mở vở (open his notebook) hay ra khỏi lớp (leave the classroom). Leo đã sẵn sàng tham gia cùng các bạn!'}
 ]}
];
